// Generated by 'unplugin-auto-import'
export {}
declare global {
  const CvMessage: typeof import('cloudview.ui-next')['CvMessage']
  const CvMessageBox: typeof import('cloudview.ui-next')['CvMessageBox']
}
