export const FileKeyMaps = {
    '点号': 'gin',
    '原始地址': 'register',
    '原始名': 'name',
    // '子类型': 'subtype',
    '遥测子类型': 'ycsubtype',
    '遥信子类型': 'yxsubtype',
    '遥脉子类型': 'ymsubtype',
    '数据类型': 'datatype',
    '功能码': 'code',
    '位偏移': 'bitoffset',
    '偏移量': 'offset',
    '系数': 'coeff',
    '单位': 'unit',
    '上限': 'upperlimit',
    '下限': 'lowerlimit',
    '计算点': 'calculated',
    '人工置数点': 'manual',
    '报警允许': 'enablewarning',
    '是否转发': 'trans',
    '历史存盘周期': 'hisperiod',
    'MqttKey': 'mqttkey',
    '取反': 'negation',
    '满刻度值': 'fullscalevalue',
    '控制模式': 'ctlmode',
    '相关遥信': 'relatedigital',
    '遥控超时时间': 'controltimeout',
    '相关遥测': 'relateanalog',
    '下发系数': 'coeff',
    '遥调上限': 'uplimit',
    '遥调下限': 'lowlimit',
    '遥调超时时间': 'adjusttimeout',
    '值类型':'valuetype'
} as const;
