import type {IPrimitive} from '../types';
import {EngineTypeEnum, PrimitiveTypeAllEnum} from '../types';
import {LinePathType} from '@cloudview.visualization-next/services';

export const BasicLine: IPrimitive = {
    description: 'Line',
    enabled: true,
    engine_type: EngineTypeEnum['2D'],
    id: '4da880f6-f67c-11eb-90ca-acde48001122',
    model_id: 'svg-line-model-id',
    model: `<svg id="图层_1" data-name="图层 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 99.99 1"><defs><style>.cls-1{fill:none;stroke:#000;stroke-miterlimit:10;}</style></defs><title>line</title><line class="cls-1" y1="0.5" x2="99.99" y2="0.5"/></svg>`,
    name: 'Line',
    vnb_id: '',
    public: false,
    tag: 'BASIC',
    type: PrimitiveTypeAllEnum.LINE,
    isBasic: true,
    content: {
        attributes: {
            x: 0,
            y: 0,
            posList: [
                {
                    type: LinePathType.L,
                    x: 100,
                    y: 0,
                },
            ],
            opacity: 1,
            'end-arrow': '0',
            'start-arrow': '0',
            stroke: '#000',
            'stroke-dasharray': '0 0',
            'stroke-opacity': 1,
            'stroke-width': 5,
            'background-color': '#000',
            'background-opacity': 1,
            'background-width': 10,
            'background-visible': false,
            rotate: 0,
            flash: false,
            'flash-begin': 0,
            'flash-dur': 0.5,
            'stream-animation': false,
            'stream-direction-reverse': false,
            'stream-speed': 1,
            title: '',
        },
        userDefined: {},
    },
};

export const BasicText: IPrimitive = {
    description: 'Text',
    enabled: true,
    engine_type: EngineTypeEnum['2D'],
    id: '717b6a7a-f67c-11eb-90ca-acde48001122',
    model_id: 'text-model-id',
    model: `<svg  xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="50.48px" height="24.95px" viewBox="0 0 50.48 24.95" enable-background="new 0 0 50.48 24.95" xml:space="preserve"><rect y="0" fill="none" width="50.48" height="24.9"/><text transform="matrix(1 0 0 1 2.5 19.3604)" font-family="'AdobeSongStd-Light-GBpc-EUC-H'" font-size="22px">Text</text></svg>`,
    name: 'Text',
    vnb_id: '',
    public: false,
    tag: 'BASIC',
    type: PrimitiveTypeAllEnum.TEXT,
    isBasic: true,
    content: {
        attributes: {
            x: 0,
            y: 0,
            width: 100,
            height: 50,
            opacity: 1,
            'background-color': null,
            color: null,
            'font-size': 14,
            'font-weight': false,
            'font-style': false,
            'text-decoration-line': false,
            'text-align': 'center',
            'vertical-align': 'middle',
            rotate: 0,
            'horizontal-flip': false,
            'vertical-flip': false,
            flash: false,
            'flash-begin': 0,
            'flash-dur': 0.5,
            title: '',
            'content-prefix': '',
            content: 'Text',
            'content-suffix': '',
            style: '',
        },
        userDefined: {},
    },
};

export const BasicRect: IPrimitive = {
    description: 'Rect',
    enabled: true,
    engine_type: EngineTypeEnum['2D'],
    id: '68126146-f67c-11eb-90ca-acde48001122',
    model_id: 'svg-rect-model-id',
    model: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 60"><defs><style>.cls-1{fill:#fff;}</style></defs><title>rect</title><rect class="cls-1" x="0.5" y="0.5" width="99" height="59"/><path d="M99,1V59H1V1H99m1-1H0V60H100V0Z"/></svg>`,
    name: 'Rect',
    vnb_id: '',
    public: false,
    tag: 'BASIC',
    type: PrimitiveTypeAllEnum.RECT,
    isBasic: true,
    content: {
        attributes: {
            x: 0,
            y: 0,
            width: 100,
            height: 50,
            'fill-opacity': 1,
            fill: '#FFFFFF',
            opacity: 1,
            stroke: '#000',
            'stroke-dasharray': '',
            'stroke-opacity': 1,
            'stroke-width': 1,
            rotate: 0,
            'horizontal-flip': false,
            'vertical-flip': false,
            flash: false,
            'flash-begin': 0,
            'flash-dur': 0.5,
            title: '',
        },
        userDefined: {},
    },
};

export const BasicEllipse: IPrimitive = {
    description: 'Ellipse',
    enabled: true,
    engine_type: EngineTypeEnum['2D'],
    id: '5d64b83e-f67c-11eb-90ca-acde48001122',
    isBasic: true,
    model_id: 'svg-ellipse-model-id',
    model: `<?xml version="1.0" encoding="utf-8"?><!-- Generator: Adobe Illustrator 23.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --><svg id="图层_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="200px" height="120px" viewBox="0 0 200 120" enable-background="new 0 0 200 120" xml:space="preserve"><g><ellipse fill="#FFFFFF" stroke="#000000" stroke-width="2" cx="100" cy="60" rx="99.5" ry="59.5"/></g></svg>`,
    name: 'Ellipse',
    vnb_id: '',
    public: false,
    tag: 'BASIC',
    type: PrimitiveTypeAllEnum.ELLIPSE,
    content: {
        attributes: {
            cx: 50,
            cy: 50,
            rx: 50,
            ry: 50,
            'fill-opacity': 1,
            fill: '#FFFFFF',
            opacity: 1,
            stroke: '#000',
            'stroke-dasharray': '',
            'stroke-opacity': 1,
            'stroke-width': 1,
            rotate: 0,
            'horizontal-flip': false,
            'vertical-flip': false,
            flash: false,
            'flash-begin': 0,
            'flash-dur': 0.5,
            title: '',
        },
        userDefined: {},
    },
};
