import type {ILineAttrConfig} from '../types';
import {AttrTypeEnum} from '../tokens';

export default function getLineAttrConfig(): ILineAttrConfig {
    return {
        // svg相关属性
        'x': {
            // 终点的x坐标
            'id': 'x',
            'type': AttrTypeEnum.NUMBER,
            'value': 100,
            'step': 1,
            'tag': 'Arrange',
            'name': 'vis.common.x',
            'readonly': false,
            'desc': 'vis.property.xDesc',
            'attrType': 'svg',
            needMin: false,
            needMax: false,
            hiddenInPrimitive: false,
        },
        'y': {
            // 终点的y坐标
            'id': 'y',
            'type': AttrTypeEnum.NUMBER,
            'value': 50,
            'step': 1,
            'tag': 'Arrange',
            'name': 'vis.common.y',
            'readonly': false,
            'desc': 'vis.property.yDesc',
            'attrType': 'svg',
            needMin: false,
            needMax: false,
            hiddenInPrimitive: false,
        },
        'opacity': {
            // 0~1, 图元整体透明度，默认1
            'id': 'opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.opacity',
            'readonly': false,
            'desc': 'vis.property.opacityDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke': {
            // 外轮廓的颜色，默认黑色
            'id': 'stroke',
            'type': AttrTypeEnum.COLOR,
            'value': '#000000',
            'tag': 'Style',
            'name': 'vis.property.strokeColor',
            'readonly': false,
            'desc': 'vis.property.strokeColorDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke-dasharray': {
            // 外轮廓的虚线范式，默认无
            'id': 'stroke-dasharray',
            'type': AttrTypeEnum.STROKE_DASHARRAY,
            'value': '0 0',
            'tag': 'Style',
            'name': 'vis.property.strokeStyle',
            'readonly': false,
            'desc': 'vis.property.strokeStyleDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke-opacity': {
            // 0~1，外轮廓的透明度，默认1
            'id': 'stroke-opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.strokeOpacity',
            'readonly': false,
            'desc': 'vis.property.strokeOpacityDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke-width': {
            // 外轮廓的宽度，默认0
            'id': 'stroke-width',
            'type': AttrTypeEnum.NUMBER,
            'value': 5,
            'needMin': true,
            needMax: false,
            'min': 0,
            'step': 1,
            'tag': 'Style',
            'name': 'vis.property.strokeWidth',
            'readonly': false,
            'desc': 'vis.property.strokeWidthDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        /*
        'start-arrow': {
            id: 'start-arrow',
            'type': AttrTypeEnum.LINE_ARROW,
            'value': '0',
            'tag': 'Style',
            'name': 'vis.property.lineStartArrow',
            'readonly': false,
            'desc': 'vis.property.lineStartArrowDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        'end-arrow': {
            id: 'end-arrow',
            'type': AttrTypeEnum.LINE_ARROW,
            'value': '0',
            'tag': 'Style',
            'name': 'vis.property.lineEndArrow',
            'readonly': false,
            'desc': 'vis.property.lineEndArrowDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        */
        'background-color': {
            // 背景的颜色，默认黑色
            'id': 'background-color',
            'type': AttrTypeEnum.COLOR,
            'value': '#000000',
            'tag': 'Style',
            'name': 'vis.property.backgroundColor',
            'readonly': false,
            'desc': 'vis.property.backgroundColorDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'background-visible': {
            // 背景是否显示，默认不显示
            'id': 'background-visible',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Style',
            'name': 'vis.property.backgroundVisible',
            'readonly': false,
            'desc': 'vis.property.backgroundVisibleDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'background-opacity': {
            // 背景的透明度，默认1
            'id': 'background-opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.backgroundOpacity',
            'readonly': false,
            'desc': 'vis.property.backgroundOpacityDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'background-width': {
            // 背景的高度，默认10
            'id': 'background-width',
            'type': AttrTypeEnum.NUMBER,
            'value': 10,
            'needMin': true,
            needMax: false,
            'min': 0,
            'step': 1,
            'tag': 'Style',
            'name': 'vis.property.backgroundWidth',
            'readonly': false,
            'desc': 'vis.property.backgroundWidthDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        // 事件属性
        'click': {
            'id': 'click',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.clickEvent',
            'readonly': false,
            'desc': 'vis.property.clickDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        'dblclick': {
            'id': 'dblclick',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.dblclickEvent',
            'readonly': false,
            'desc': 'vis.property.dblClickDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        'mouseenter': {
            'id': 'mouseenter',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.mouseover',
            'readonly': false,
            'desc': 'vis.property.mouseoverDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        'mouseleave': {
            'id': 'mouseleave',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.mouseout',
            'readonly': false,
            'desc': 'vis.property.mouseoutDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        //其他属性，需要各个类型的图元自定义生效模式
        'title': {
            'id': 'title',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Info',
            'name': 'vis.property.title',
            'readonly': false,
            'desc': 'vis.property.titleDesc',
            'attrType': 'other',
            hiddenInPrimitive: false,
        },
        'stream-animation': {
            'id': 'stream-animation',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Animation',
            'name': 'vis.property.streamAnimation',
            'readonly': false,
            'desc': 'vis.property.streamAnimationDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
        'stream-direction-reverse': {
            'id': 'stream-direction-reverse',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Animation',
            'name': 'vis.property.streamDirectionReverse',
            'readonly': false,
            'desc': 'vis.property.streamDirectionReverseDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
        'stream-speed': {
            // 背景的透明度，默认1
            'id': 'stream-speed',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 1,
            'max': 10,
            'step': 1,
            'tag': 'Style',
            'name': 'vis.property.streamSpeed',
            'readonly': false,
            'desc': 'vis.property.streamSpeedDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'flash': {
            'id': 'flash',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Animation',
            'name': 'vis.property.animationFlash',
            'readonly': false,
            'desc': 'vis.property.animationFlashDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
        'flash-dur': {
            'id': 'flash-dur',
            'type': AttrTypeEnum.NUMBER,
            'value': 0.5,
            'min': 0,
            'needMin': true,
            needMax: false,
            'step': 1,
            'tag': 'Animation',
            'name': 'vis.property.animationFlashDur',
            'readonly': false,
            'desc': 'vis.property.animationFlashDurDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
        'flash-begin': {
            'id': 'flash-begin',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'min': 0,
            'needMin': true,
            needMax: false,
            'step': 1,
            'tag': 'Animation',
            'name': 'vis.property.animationFlashBegin',
            'readonly': false,
            'desc': 'vis.property.animationFlashBeginDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
    };
}
