import type {IRectAttrConfig} from '../types';
import {AttrTypeEnum} from '../tokens';

export default function getRectAttrConfig(): IRectAttrConfig {
    return {
        // svg相关属性
        'x': {
            // 起点x轴坐标
            'id': 'x',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'step': 1,
            needMin: false,
            needMax: false,
            'tag': 'Arrange',
            'name': 'vis.common.bigX', // 属性名
            'readonly': false,
            'desc': 'vis.property.xDesc',
            'attrType': 'svg',
            hiddenInPrimitive: true,
        },
        'y': {
            // 起点y轴坐标
            'id': 'y',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'step': 1,
            needMin: false,
            needMax: false,
            'tag': 'Arrange',
            'name': 'vis.common.bigY',
            'readonly': false,
            'desc': 'vis.property.yDesc',
            'attrType': 'svg',
            hiddenInPrimitive: true,
        },
        'width': {
            'id': 'width',
            'type': AttrTypeEnum.NUMBER,
            'value': 100,
            'needMin': true,
            'min': 0,
            needMax: false,
            'step': 1,
            'tag': 'Arrange',
            'name': 'vis.property.width',
            'readonly': false,
            'desc': 'vis.property.widthDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'height': {
            'id': 'height',
            'type': AttrTypeEnum.NUMBER,
            'value': 60,
            'needMin': true,
            'min': 0,
            needMax: false,
            'step': 1,
            'tag': 'Arrange',
            'name': 'vis.property.height',
            'readonly': false,
            'desc': 'vis.property.heightDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'opacity': {
            // 0~1, 图元整体透明度，默认1
            'id': 'opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.opacity',
            'readonly': false,
            'desc': 'vis.property.opacityDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'fill': {
            'id': 'fill',
            'type': AttrTypeEnum.COLOR,
            'value': '#FFFFFF',
            'tag': 'Style',
            'name': 'vis.property.fillColor',
            'readonly': false,
            'desc': 'vis.property.fillColorDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'fill-opacity': {
            'id': 'fill-opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.fillOpacity',
            'readonly': false,
            'desc': 'vis.property.fillOpacityDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke': {
            // 外轮廓的颜色，默认黑色
            'id': 'stroke',
            'type': AttrTypeEnum.COLOR,
            'value': '#000000',
            'tag': 'Style',
            'name': 'vis.property.strokeColor',
            'readonly': false,
            'desc': 'vis.property.strokeColorDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke-dasharray': {
            // 外轮廓的虚线范式，默认无
            'id': 'stroke-dasharray',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Style',
            'name': 'vis.property.strokeStyle',
            'readonly': false,
            'desc': 'vis.property.strokeStyleDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke-opacity': {
            // 0~1，外轮廓的透明度，默认1
            'id': 'stroke-opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.strokeOpacity',
            'readonly': false,
            'desc': 'vis.property.strokeOpacityDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'stroke-width': {
            // 外轮廓的宽度，默认1
            'id': 'stroke-width',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'min': 0,
            needMax: false,
            'step': 1,
            'tag': 'Style',
            'name': 'vis.property.strokeWidth',
            'readonly': false,
            'desc': 'vis.property.strokeWidthDesc',
            'attrType': 'svg',
            hiddenInPrimitive: false,
        },
        'rotate': {
            'id': 'rotate',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'step': 1,
            needMax: false,
            needMin: false,
            'tag': 'Arrange',
            'name': 'vis.property.rotate',
            'readonly': false,
            'desc': 'vis.property.rotateDesc',
            'attrType': 'transform',
            hiddenInPrimitive: false,
        },
        'horizontal-flip': {
            'id': 'horizontal-flip',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Arrange',
            'name': 'vis.property.horizontalFlip',
            'readonly': false,
            'desc': 'vis.property.horizontalFlipDesc',
            'attrType': 'transform',
            hiddenInPrimitive: false,
        },
        'vertical-flip': {
            'id': 'vertical-flip',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Arrange',
            'name': 'vis.property.verticalFlip',
            'readonly': false,
            'desc': 'vis.property.verticalFlipDesc',
            'attrType': 'transform',
            hiddenInPrimitive: false,
        },
        // 事件属性
        'click': {
            'id': 'click',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.clickEvent',
            'readonly': false,
            'desc': 'vis.property.clickDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        'dblclick': {
            'id': 'dblclick',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.dblclickEvent',
            'readonly': false,
            'desc': 'vis.property.dblClickDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        'mouseenter': {
            'id': 'mouseenter',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.mouseover',
            'readonly': false,
            'desc': 'vis.property.mouseoverDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        'mouseleave': {
            'id': 'mouseleave',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.mouseout',
            'readonly': false,
            'desc': 'vis.property.mouseoutDesc',
            'attrType': 'event',
            hiddenInPrimitive: true,
            disabled: true,
        },
        //其他属性，需要各个类型的图元自定义生效模式
        'title': {
            'id': 'title',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Info',
            'name': 'vis.property.title',
            'readonly': false,
            'desc': 'vis.property.titleDesc',
            'attrType': 'other',
            hiddenInPrimitive: false,
        },
        'flash': {
            'id': 'flash',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Animation',
            'name': 'vis.property.animationFlash',
            'readonly': false,
            'desc': 'vis.property.animationFlashDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
        'flash-dur': {
            'id': 'flash-dur',
            'type': AttrTypeEnum.NUMBER,
            'value': 0.5,
            'min': 0,
            'needMin': true,
            needMax: false,
            'step': 1,
            'tag': 'Animation',
            'name': 'vis.property.animationFlashDur',
            'readonly': false,
            'desc': 'vis.property.animationFlashDurDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
        'flash-begin': {
            'id': 'flash-begin',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'min': 0,
            'needMin': true,
            needMax: false,
            'step': 1,
            'tag': 'Animation',
            'name': 'vis.property.animationFlashBegin',
            'readonly': false,
            'desc': 'vis.property.animationFlashBeginDesc',
            'attrType': 'animation',
            hiddenInPrimitive: false,
        },
    };
}
