import type {ITextAttrConfig} from '../types';
import {AttrTypeEnum} from '../tokens';

export default function getTextAttrConfig(): ITextAttrConfig {
    return {
        'x': {
            // 图元x轴坐标
            'id': 'x',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'step': 1,
            'needMax': false,
            'needMin': false,
            'tag': 'Arrange',
            'name': 'vis.common.bigX',
            'readonly': false,
            'desc': 'vis.property.xDesc',
            'attrType': 'svg',
            'hiddenInPrimitive': true,
        },
        'y': {
            // 图元y轴坐标
            'id': 'y',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'step': 1,
            'needMax': false,
            'needMin': false,
            'tag': 'Arrange',
            'name': 'vis.common.bigY',
            'readonly': false,
            'desc': 'vis.property.yDesc',
            'attrType': 'svg',
            'hiddenInPrimitive': true,
        },
        'width': {
            'id': 'width',
            'type': AttrTypeEnum.NUMBER,
            'value': 50,
            'needMin': true,
            'min': 0,
            'needMax': false,
            'step': 1,
            'tag': 'Arrange',
            'name': 'vis.property.width',
            'readonly': false,
            'desc': 'vis.property.widthDesc',
            'attrType': 'svg',
            'hiddenInPrimitive': false,
        },
        'height': {
            'id': 'height',
            'type': AttrTypeEnum.NUMBER,
            'value': 100,
            'needMin': true,
            'min': 0,
            'needMax': false,
            'step': 1,
            'tag': 'Arrange',
            'name': 'vis.property.height',
            'readonly': false,
            'desc': 'vis.property.heightDesc',
            'attrType': 'svg',
            'hiddenInPrimitive': false,
        },
        'rotate': {
            'id': 'rotate',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'step': 1,
            'needMax': false,
            'needMin': false,
            'tag': 'Arrange',
            'name': 'vis.property.rotate',
            'readonly': false,
            'desc': 'vis.property.rotateDesc',
            'attrType': 'transform',
            'hiddenInPrimitive': false,
        },
        'horizontal-flip': {
            'id': 'horizontal-flip',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Arrange',
            'name': 'vis.property.horizontalFlip',
            'readonly': false,
            'desc': 'vis.property.horizontalFlipDesc',
            'attrType': 'transform',
            'hiddenInPrimitive': false,
        },
        'vertical-flip': {
            'id': 'vertical-flip',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Arrange',
            'name': 'vis.property.verticalFlip',
            'readonly': false,
            'desc': 'vis.property.verticalFlipDesc',
            'attrType': 'transform',
            'hiddenInPrimitive': false,
        },
        // css相关属性
        'opacity': {
            // 0~1, 图元整体透明度，默认1
            'id': 'opacity',
            'type': AttrTypeEnum.NUMBER,
            'value': 1,
            'needMin': true,
            'needMax': true,
            'min': 0,
            'max': 1,
            'step': 0.1,
            'tag': 'Style',
            'name': 'vis.property.opacity',
            'readonly': false,
            'desc': 'vis.property.opacityDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'background-color': {
            // 图元背景色，默认无
            'id': 'background-color',
            'type': AttrTypeEnum.COLOR,
            'value': null,
            'tag': 'Style',
            'name': 'vis.property.background',
            'readonly': false,
            'desc': 'vis.property.backgroundDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'color': {
            // 文字颜色，默认黑色
            'id': 'color',
            'type': AttrTypeEnum.COLOR,
            'value': '#333333',
            'tag': 'Text',
            'name': 'vis.property.textColor',
            'readonly': false,
            'desc': 'vis.property.textColorDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'font-size': {
            // 文字大小，默认12px
            'id': 'font-size',
            'type': AttrTypeEnum.NUMBER,
            'value': 12,
            'needMin': true,
            'min': 12,
            'needMax': false,
            'step': 1,
            'tag': 'Text',
            'name': 'vis.property.fontSize',
            'readonly': false,
            'desc': 'vis.property.fontSizeDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'font-weight': {
            // 文字加粗
            'id': 'font-weight',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Text',
            'name': 'vis.property.fontWeight',
            'readonly': false,
            'desc': 'vis.property.fontWeightDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'font-style': {
            // 斜体
            'id': 'font-style',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Text',
            'name': 'vis.property.fontStyle',
            'readonly': false,
            'desc': 'vis.property.fontStyleDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'text-decoration-line': {
            // 装饰器
            'id': 'text-decoration-line',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Text',
            'name': 'vis.property.textLine',
            'readonly': false,
            'desc': 'vis.property.textLineDesc',
            'attrType': 'css',
            'hiddenInPrimitive': false,
        },
        'text-align': {
            // 文字水平方向对齐方式
            'id': 'text-align',
            'type': AttrTypeEnum.SELECT,
            'value': 'center',
            'tag': 'Text',
            'name': 'vis.property.textAlign',
            'readonly': false,
            'desc': 'vis.property.textAlignDesc',
            'attrType': 'css',
            'options': [
                {
                    value: 'center',
                    label: 'center',
                },
                {
                    value: 'left',
                    label: 'left',
                },
                {
                    value: 'right',
                    label: 'right',
                },
            ],
            'hiddenInPrimitive': false,
        },
        'vertical-align': {
            // 文字垂直方向对齐方式
            'id': 'vertical-align',
            'type': AttrTypeEnum.SELECT,
            'value': 'middle',
            'tag': 'Text',
            'name': 'vis.property.verticalAlign',
            'readonly': false,
            'desc': 'vis.property.verticalAlignDesc',
            'attrType': 'css',
            'options': [
                {
                    value: 'middle',
                    label: 'middle',
                },
                {
                    value: 'top',
                    label: 'top',
                },
                {
                    value: 'bottom',
                    label: 'bottom',
                },
            ],
            'hiddenInPrimitive': false,
        },
        // 事件属性
        'click': {
            'id': 'click',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.clickEvent',
            'readonly': false,
            'desc': 'vis.property.clickDesc',
            'attrType': 'event',
            'hiddenInPrimitive': true,
            'disabled': true,
        },
        'dblclick': {
            'id': 'dblclick',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.dblclickEvent',
            'readonly': false,
            'desc': 'vis.property.dblClickDesc',
            'attrType': 'event',
            'hiddenInPrimitive': true,
            disabled: true,
        },
        'mouseenter': {
            'id': 'mouseenter',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.mouseover',
            'readonly': false,
            'desc': 'vis.property.mouseoverDesc',
            'attrType': 'event',
            'hiddenInPrimitive': true,
            'disabled': true,
        },
        'mouseleave': {
            'id': 'mouseleave',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Event',
            'name': 'vis.property.mouseout',
            'readonly': false,
            'desc': 'vis.property.mouseoutDesc',
            'attrType': 'event',
            'hiddenInPrimitive': true,
            'disabled': true,
        },
        //其他属性，需要各个类型的图元自定义生效模式
        'title': {
            'id': 'title',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Info',
            'name': 'vis.property.title',
            'readonly': false,
            'desc': 'vis.property.titleDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        'style': {
            'id': 'style',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Style',
            'name': 'vis.property.style',
            'readonly': false,
            'desc': 'vis.property.styleDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        'content-prefix': {
            'id': 'content-prefix',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Info',
            'name': 'vis.property.textContentPrefix',
            'readonly': false,
            'desc': 'vis.property.textContentPrefixDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        'content': {
            'id': 'content',
            'type': AttrTypeEnum.TEXT,
            'value': 'Text',
            'tag': 'Info',
            'name': 'vis.property.textContent',
            'readonly': false,
            'desc': 'vis.property.textContentDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        'content-suffix': {
            'id': 'content-suffix',
            'type': AttrTypeEnum.TEXT,
            'value': '',
            'tag': 'Info',
            'name': 'vis.property.textContentSuffix',
            'readonly': false,
            'desc': 'vis.property.textContentSuffixDesc',
            'attrType': 'other',
            'hiddenInPrimitive': false,
        },
        'flash': {
            'id': 'flash',
            'type': AttrTypeEnum.BOOLEAN,
            'value': false,
            'tag': 'Animation',
            'name': 'vis.property.animationFlash',
            'readonly': false,
            'desc': 'vis.property.animationFlashDesc',
            'attrType': 'animation',
            'hiddenInPrimitive': false,
        },
        'flash-dur': {
            'id': 'flash-dur',
            'type': AttrTypeEnum.NUMBER,
            'value': 0.5,
            'min': 0,
            'needMin': true,
            'needMax': false,
            'step': 1,
            'tag': 'Animation',
            'name': 'vis.property.animationFlashDur',
            'readonly': false,
            'desc': 'vis.property.animationFlashDurDesc',
            'attrType': 'animation',
            'hiddenInPrimitive': false,
        },
        'flash-begin': {
            'id': 'flash-begin',
            'type': AttrTypeEnum.NUMBER,
            'value': 0,
            'min': 0,
            'needMin': true,
            'needMax': false,
            'step': 1,
            'tag': 'Animation',
            'name': 'vis.property.animationFlashBegin',
            'readonly': false,
            'desc': 'vis.property.animationFlashBeginDesc',
            'attrType': 'animation',
            'hiddenInPrimitive': false,
        },
    };
}
